### PR TITLE
Update version of docker-py to 1.4.0

### PR DESCRIPTION
**Pull request by losipiuk**
This is nothing crucial.
Just result of searching around trying to make tests run on boot2docker.
Does not seem to break anything though. You may merge it some time later if you like.

### CODE REVIEW

**Comment by rschlussel** [comment]
I think we were intentionally on an older version because the newer version was causing some failure (I don't remember exactly what).  Could you run all the tests with this?

**Comment by cawallin** [comment]
yeah, here's the PR: https://github.com/prestodb/presto-admin/pull/9.  It has to do with both the version of docker you have installed and the client version, so if this doesn't help the boot2docker stuff it'd be better for this change not to go in

**Comment by losipiuk** [comment]
I am currently on newest docker. Updating docker-py was just a try - it did not help - so I will not be forcing update. Probably after the release we can think of freshening libraries up. Users will probably have newest docker installed and at some point old docker-py may stop working with that.

**Comment by ebd2** [comment]
I think we can close this one; I updated to docker-py 1.5.0 a little bit ago :-)

**Comment by cawallin** [comment]
sure, go ahead

**Pull request closed without merging**
