### PR TITLE
Remove dummy-rpm.rpm usage from product tests

### PR DESCRIPTION
**Pull request by kokosing**
Remove dummy-rpm.rpm usage from product tests

Mocking rpm file in product tests does not much black-box testing.

### CODE REVIEW

**Comment by losipiuk** [comment]
lgtm - but please fix the commit message.

**Comment by ebd2** [comment]
I don't love the amount of time we're going to be adding to the test runs, but I'm not running these locally at the moment, and we can probably address the by taking another look at the tests instead of using a dummy RPM.

LGTM.

**Comment by cawallin** [comment]
lgtm

**Comment by ebd2** [comment]
Updated commit message and merged.

**Pull request closed without merging**
