### PR TITLE
Execute “rpm  -U" when "server upgrade" task

### PR DESCRIPTION
**Pull request by yuokada**
I don't want to use `--nodeps` option when upgrade a rpm package  because it's dangerous.

### CODE REVIEW

**Comment by cawallin** [comment]
Thanks for the PR! I think the product test failures come because our dummy rpm (the stripped down, small RPM we use for upgrade that is checked into the repo) was created against Presto 0.153, and so it can't upgrade to the most recent version. We unfortunately don't have the process of making a dummy rpm documented, so I can make one for this and give it some extremely high version so we don't run into this again (like Presto 10.100 or something)

**Comment by yuokada** [comment]
@cawallin Hi, Thanks for reply. 
I have understantd that you have only one version rpm for testing. 
And, "rpm -U ~" failed because installed rpm and Upgrade rpm is same one.
Is this correct?
So, Should I wait for your update, Shouldn't I ?

**Comment by cawallin** [comment]
@yuokada we're working on getting a new dummy RPM for these tests. The problem is, before the tests uninstalled the old RPM and then installed a dummy RPM, but now they use rpm -U. When you use rpm -U, you need to have the version of the new RPM higher than the version of the old RPM, but the dummy RPM's version was 0.153. We're working on getting you a new dummy RPM now.

**Comment by cawallin** [comment]
@yuokada -- we have a dummy rpm that works, I sent it to you on slack.
With this RPM, the only test failure is with test_rolling_upgrade, which is redundant with your -U change. You can remove it.

**Comment by cawallin** [comment]
Also, please remove the documentation about --nodeps from the upgrade() function in server.py, since it's not allowed in server upgrade now. (it's still allowed for package install, which seems fine by me)

**Comment by amrutagokhale** [comment]
@yuokada We have uploaded the new dummy rpm to the master branch. If you rebase your PR against the latest master, the failures should go away.

**Comment by yuokada** [comment]
> "[slave2] out: 	package presto-server-rpm-0:100.100.SNAPSHOT-1.x86_64 is already installed"

HM?
https://travis-ci.org/prestodb/presto-admin/jobs/202098819
```
[slave2] out: Stopping presto 
[slave2] out: Not running
[slave2] out: 
[slave2] out: /tmp/presto_config-FdEuLFE.tar
[slave2] out: 
Deploying rpm on slave2...
Package deployed successfully on: slave2
[slave2] out: 	package presto-server-rpm-0:100.100.SNAPSHOT-1.x86_64 is already installed
[slave2] out: 
Fatal error: [slave1] sudo() received nonzero return code 1 while executing!
Requested
```

**Comment by yuokada** [comment]
> We'll merge it shortly.

OK,  I remove "[WIP]" in title.

**Comment by amrutagokhale** [comment]
Merged, thanks!

**Pull request closed without merging**
