### PR TITLE
Refactor direct variable references to getter calls

### PR DESCRIPTION
**Pull request by petroav**

### CODE REVIEW

**Comment by petroav** [comment]
@rschlussel & @ebd2 
Passing Travis build: https://travis-ci.org/Teradata/presto-admin/builds/163465862

**Comment by rschlussel** [comment]
I think we should use properties instead http://docs.quantifiedcode.com/python-anti-patterns/correctness/implementing_java-style_getters_and_setters.html

**Comment by petroav** [comment]
Good suggestion, I'll re-write the commit accordingly.

**Comment by petroav** [comment]
Superseded by https://github.com/prestodb/presto-admin/pull/276

**Pull request closed without merging**
