### PR TITLE
Remove plugin that was added by the test

### PR DESCRIPTION
**Pull request by cawallin**
* necessary to remove artifacts for configurable cluster testing

Testing: ran plugin tests

### CODE REVIEW

**Comment by cawallin** [comment]
@rschlussel

**Comment by rschlussel** [comment]
Did you run tests on the plugin/uninstall tests on a real cluster?

**Comment by rschlussel** [comment]
lgtm assuming testing

**Comment by cawallin** [comment]
Yeah, it works on a real cluster

**Pull request closed without merging**
