### PR TITLE
Collect connectors

### PR DESCRIPTION
**Pull request by rschlussel**

### CODE REVIEW

**Comment by akshatnair** [comment]
LGTM but what about docs? https://github.com/prestodb/presto-admin/blob/master/docs/presto-admin-commands.rst

**Comment by rschlussel** [comment]
The docs already say they get info about connectors configured, so I thought this was just more info. Would you rather I explicitly say that it gathers connector configuration files?

**Comment by akshatnair** [comment]
my bad I thought this was a new command

**Comment by akshatnair** [comment]
but that I think meant the name from server status? but now we also collect the config details so maybe add a line connectors configurations rather than connectors configured?

**Comment by rschlussel** [comment]
done (squashed it into the last commit)

**Comment by rschlussel** [comment]
merged

**Pull request closed without merging**
