### PR TITLE
Refactor coordinator and worker to be classes

### PR DESCRIPTION
**Pull request by rschlussel**
Refactor coordinator and worker configuration code to inherit from an
abstract Node class.  This reduces code duplication

Testing: make test, test_configuration product tests

The changes to coordinator and worker are a bit hard to read in the diff, but basically all that happened is everything got indented to be under the Coordinator or Worker class.  And the get_conf method was moved out to the abstract Node class.

### CODE REVIEW

**Comment by rschlussel** [comment]
@ebd2 @cawallin

**Comment by cawallin** [comment]
This is just refactoring, right, not fixing the config default stuff? if so, looks good

**Comment by rschlussel** [comment]
yup.  Just refactoring

**Comment by ebd2** [comment]
LGTM. Thanks!

**Comment by rschlussel** [comment]
merged

**Pull request closed without merging**
