### PR TITLE
Release 1.4.1

### PR DESCRIPTION
**Pull request by cawallin**

### CODE REVIEW

**Comment by zachyee** [comment]
Add `release/release-1.4.1` to `docs/release.rst`

**Comment by cawallin** [comment]
Good call, thanks

**Comment by cawallin** [comment]
updated

**Comment by rschlussel** [comment]
should this be release 1.5 because of the added support for 0.149+?  Seems like a significant change (definitely bigger than the difference between 1.2 and 1.3)

**Pull request closed without merging**
